### PR TITLE
Update worldcup.json

### PR DESCRIPTION
**Pull request by GonrasK**

### CODE REVIEW

**Comment by geraldb** [comment]
@GonrasK  Your help is greatly appreciated. Please, update the source <https://github.com/openfootball/world-cup/blob/master/2018--russia/cup.txt>, the json files get auto-generated (and always overwritten) from the (source) text files.

**Comment by GonrasK** [comment]
but aren't the scores supposed to get updated as well in the json?

**Comment by geraldb** [comment]
Yes, but with a script once the source gets updated, please read the the readme :-).

**Comment by GonrasK** [comment]
I'm sorry, I read it, and I still don't understand how can i manually contribute to the source .txt file?

**Comment by Arlantir** [comment]
The file has been updated, but JSON does not exist

**Comment by geraldb** [comment]
Instead of editing / updating the json file you are more than welcome to edit / update source text file <https://github.com/openfootball/world-cup/blob/master/2018--russia/cup.txt>. That is, step 1. Step 2 to is running the script to auto-generate the json files (with a script). PS: Please send more questions to the forum / mailing list <http://groups.google.com/group/opensport>.

**Pull request closed without merging**
